/*------------------------------------------------------------------------------
 * This code was generated by Spiral IIR Filter Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */
/* ./iirGen.pl -A 256 0 661 0 673 0 349 0 99 0 15 0 1 0 0 0 0 0 0 0 -B 0 0 0 3 15 45 106 197 296 362 362 296 197 106 45 15 3 0 0 0 -moduleName IIR_filter -fractionalBits 8 -bitWidth 32 -inData inData -inReg -outReg -outData outData -clk clk -reset reset -reset_edge negedge -filterForm 1 -outFile ../outputs/filter_1498583898.v */
/* Warning: zero-valued filter taps have been optimized away. */

module IIR_filter_firBlock_left_MultiplyBlock (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17
);

  // Port mode declarations:
  input signed   [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17;

  wire [31:0] Y [0:16];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];

  //Multipliers:

  wire signed [39:0]
    w1,
    w0,
    w4,
    w3,
    w16,
    w15,
    w48,
    w45,
    w8,
    w37,
    w53,
    w180,
    w181,
    w197,
    w106,
    w296,
    w362;

  assign w1 = X;
  assign w0 = 0;
  assign w106 = w53 << 1;
  assign w15 = w16 - w1;
  assign w16 = w1 << 4;
  assign w180 = w45 << 2;
  assign w181 = w1 + w180;
  assign w197 = w181 + w16;
  assign w296 = w37 << 3;
  assign w3 = w4 - w1;
  assign w362 = w181 << 1;
  assign w37 = w45 - w8;
  assign w4 = w1 << 2;
  assign w45 = w48 - w3;
  assign w48 = w3 << 4;
  assign w53 = w45 + w8;
  assign w8 = w1 << 3;

  assign Y[0] = w3[39:8];
  assign Y[1] = w15[39:8];
  assign Y[2] = w45[39:8];
  assign Y[3] = w106[39:8];
  assign Y[4] = w197[39:8];
  assign Y[5] = w296[39:8];
  assign Y[6] = w362[39:8];
  assign Y[7] = w362[39:8];
  assign Y[8] = w296[39:8];
  assign Y[9] = w197[39:8];
  assign Y[10] = w106[39:8];
  assign Y[11] = w45[39:8];
  assign Y[12] = w15[39:8];
  assign Y[13] = w3[39:8];
  assign Y[14] = w0[39:8];
  assign Y[15] = w0[39:8];
  assign Y[16] = w0[39:8];

  //IIR_filter_firBlock_left_MultiplyBlock area estimate = 17280.6478869868;
endmodule //IIR_filter_firBlock_left_MultiplyBlock




module IIR_filter_firBlock_left (
    X,
    clk,
    Y,
    reset
);

  // Port mode declarations:
  input   [31:0] X;
  input    clk;
  output  [31:0] Y;
  input    reset;

  //registerOut
  reg [31:0] Y;
  wire [31:0] Y_in;

  always@(posedge clk or negedge reset) begin
    if(~reset) begin
      Y <= 32'h00000000;
    end  else begin
      Y <= Y_in;
    end
  end

  wire [31:0] multProducts [0:16];

  IIR_filter_firBlock_left_MultiplyBlock my_IIR_filter_firBlock_left_MultiplyBlock(
    .X(X),
    .Y1(multProducts[0]),
    .Y2(multProducts[1]),
    .Y3(multProducts[2]),
    .Y4(multProducts[3]),
    .Y5(multProducts[4]),
    .Y6(multProducts[5]),
    .Y7(multProducts[6]),
    .Y8(multProducts[7]),
    .Y9(multProducts[8]),
    .Y10(multProducts[9]),
    .Y11(multProducts[10]),
    .Y12(multProducts[11]),
    .Y13(multProducts[12]),
    .Y14(multProducts[13]),
    .Y15(multProducts[14]),
    .Y16(multProducts[15]),
    .Y17(multProducts[16])
  );

  reg [31:0] firStep[0:15];

  always@(posedge clk or negedge reset) begin
    if(~reset) begin
      firStep[0] <= 32'h00000000;
      firStep[1] <= 32'h00000000;
      firStep[2] <= 32'h00000000;
      firStep[3] <= 32'h00000000;
      firStep[4] <= 32'h00000000;
      firStep[5] <= 32'h00000000;
      firStep[6] <= 32'h00000000;
      firStep[7] <= 32'h00000000;
      firStep[8] <= 32'h00000000;
      firStep[9] <= 32'h00000000;
      firStep[10] <= 32'h00000000;
      firStep[11] <= 32'h00000000;
      firStep[12] <= 32'h00000000;
      firStep[13] <= 32'h00000000;
      firStep[14] <= 32'h00000000;
      firStep[15] <= 32'h00000000;
    end
    else begin
      firStep[0] <=  multProducts[0];
      firStep[1] <=  firStep[0] + multProducts[1];
      firStep[2] <=  firStep[1] + multProducts[2];
      firStep[3] <=  firStep[2] + multProducts[3];
      firStep[4] <=  firStep[3] + multProducts[4];
      firStep[5] <=  firStep[4] + multProducts[5];
      firStep[6] <=  firStep[5] + multProducts[6];
      firStep[7] <=  firStep[6] + multProducts[7];
      firStep[8] <=  firStep[7] + multProducts[8];
      firStep[9] <=  firStep[8] + multProducts[9];
      firStep[10] <=  firStep[9] + multProducts[10];
      firStep[11] <=  firStep[10] + multProducts[11];
      firStep[12] <=  firStep[11] + multProducts[12];
      firStep[13] <=  firStep[12] + multProducts[13];
      firStep[14] <=  firStep[13] + multProducts[14];
      firStep[15] <=  firStep[14] + multProducts[15];
    end
  end

  assign Y_in = firStep[15]+ multProducts[16];
  //IIR_filter_firBlock_left area estimate = 87441.0786142015;
endmodule //IIR_filter_firBlock_left



/* Warning: zero-valued filter taps have been optimized away. */

module IIR_filter_firBlock_right_MultiplyBlock (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12
);

  // Port mode declarations:
  input signed   [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12;

  wire [31:0] Y [0:11];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];

  //Multipliers:

  wire signed [39:0]
    w1,
    w0,
    w16,
    w15,
    w32,
    w33,
    w132,
    w99,
    w131,
    w480,
    w349,
    w792,
    w661,
    w4,
    w3,
    w12,
    w673,
    w1_,
    w15_,
    w99_,
    w349_,
    w673_,
    w661_;

  assign w1 = X;
  assign w0 = 0;
  assign w12 = w3 << 2;
  assign w131 = w132 - w1;
  assign w132 = w33 << 2;
  assign w15 = w16 - w1;
  assign w15_ = -1 * w15;
  assign w16 = w1 << 4;
  assign w1_ = -1 * w1;
  assign w3 = w4 - w1;
  assign w32 = w1 << 5;
  assign w33 = w1 + w32;
  assign w349 = w480 - w131;
  assign w349_ = -1 * w349;
  assign w4 = w1 << 2;
  assign w480 = w15 << 5;
  assign w661 = w792 - w131;
  assign w661_ = -1 * w661;
  assign w673 = w661 + w12;
  assign w673_ = -1 * w673;
  assign w792 = w99 << 3;
  assign w99 = w132 - w33;
  assign w99_ = -1 * w99;

  assign Y[0] = w1_[39:8];
  assign Y[1] = w0[39:8];
  assign Y[2] = w15_[39:8];
  assign Y[3] = w0[39:8];
  assign Y[4] = w99_[39:8];
  assign Y[5] = w0[39:8];
  assign Y[6] = w349_[39:8];
  assign Y[7] = w0[39:8];
  assign Y[8] = w673_[39:8];
  assign Y[9] = w0[39:8];
  assign Y[10] = w661_[39:8];
  assign Y[11] = w0[39:8];

  //IIR_filter_firBlock_right_MultiplyBlock area estimate = 30689.3662925147;
endmodule //IIR_filter_firBlock_right_MultiplyBlock




module IIR_filter_firBlock_right (
    X,
    clk,
    Y,
    reset
);

  // Port mode declarations:
  input   [31:0] X;
  input    clk;
  output  [31:0] Y;
  input    reset;

  //registerOut
  reg [31:0] Y;
  wire [31:0] Y_in;

  always@(posedge clk or negedge reset) begin
    if(~reset) begin
      Y <= 32'h00000000;
    end  else begin
      Y <= Y_in;
    end
  end

  wire [31:0] multProducts [0:11];

  IIR_filter_firBlock_right_MultiplyBlock my_IIR_filter_firBlock_right_MultiplyBlock(
    .X(X),
    .Y1(multProducts[0]),
    .Y2(multProducts[1]),
    .Y3(multProducts[2]),
    .Y4(multProducts[3]),
    .Y5(multProducts[4]),
    .Y6(multProducts[5]),
    .Y7(multProducts[6]),
    .Y8(multProducts[7]),
    .Y9(multProducts[8]),
    .Y10(multProducts[9]),
    .Y11(multProducts[10]),
    .Y12(multProducts[11])
  );

  reg [31:0] firStep[0:10];

  always@(posedge clk or negedge reset) begin
    if(~reset) begin
      firStep[0] <= 32'h00000000;
      firStep[1] <= 32'h00000000;
      firStep[2] <= 32'h00000000;
      firStep[3] <= 32'h00000000;
      firStep[4] <= 32'h00000000;
      firStep[5] <= 32'h00000000;
      firStep[6] <= 32'h00000000;
      firStep[7] <= 32'h00000000;
      firStep[8] <= 32'h00000000;
      firStep[9] <= 32'h00000000;
      firStep[10] <= 32'h00000000;
    end
    else begin
      firStep[0] <=  multProducts[0];
      firStep[1] <=  firStep[0] + multProducts[1];
      firStep[2] <=  firStep[1] + multProducts[2];
      firStep[3] <=  firStep[2] + multProducts[3];
      firStep[4] <=  firStep[3] + multProducts[4];
      firStep[5] <=  firStep[4] + multProducts[5];
      firStep[6] <=  firStep[5] + multProducts[6];
      firStep[7] <=  firStep[6] + multProducts[7];
      firStep[8] <=  firStep[7] + multProducts[8];
      firStep[9] <=  firStep[8] + multProducts[9];
      firStep[10] <=  firStep[9] + multProducts[10];
    end
  end

  assign Y_in = firStep[10]+ multProducts[11];
  //IIR_filter_firBlock_right area estimate = 71045.252211047;
endmodule //IIR_filter_firBlock_right




module IIR_filter (
    inData,
    clk,
    outData,
    reset
);

  // Port mode declarations:
  input   [31:0] inData;
  input    clk;
  output  [31:0] outData;
  input    reset;

  //registerIn
  reg [31:0] inData_in;

  always@(posedge clk or negedge reset) begin
    if(~reset) begin
      inData_in <= 32'h00000000;
    end  else begin
      inData_in <= inData;
    end
  end

  //registerOut
  reg [31:0] outData;
  wire [31:0] outData_in;

  always@(posedge clk or negedge reset) begin
    if(~reset) begin
      outData <= 32'h00000000;
    end  else begin
      outData <= outData_in;
    end
  end

  wire [31:0] leftOut, rightOut;

  IIR_filter_firBlock_left my_IIR_filter_firBlock_left(
    .X(inData_in),
    .Y(leftOut),
    .clk(clk),
    .reset(reset)
);

  IIR_filter_firBlock_right my_IIR_filter_firBlock_right(
    .X(outData_in),
    .Y(rightOut),
    .clk(clk),
    .reset(reset)
);

  assign outData_in = leftOut + rightOut;

  //IIR_filter area estimate = 165578.215821322;
endmodule //IIR_filter

