/***********************************************                         
  DO NOT MODIFY THE CONTENTS OF THIS FILE.                              
  This header file has been auto-generated by xmelab.                        
  This should be included in user'c C file to                        
  facilitate the calling of imported tasks and functions.                        
************************************************/                        

#include "svdpi.h" 

#ifdef __cplusplus                          
    extern "C" {                          
#endif 

typedef struct { 
	int _a0;
 	int _a1;
 	int _a2;
 	unsigned int _a3;
 	unsigned int _a4;
 	unsigned int _a5;
 	unsigned long long _a6;
 	unsigned long long _a7[32];
 	char _a8[256];
 	char _a9[256];
 } v2c_top__mailBox;


typedef struct { 
	int _a0;
 	int _a1;
 	int _a2;
 	unsigned int _a3;
 	unsigned int _a4;
 	unsigned int _a5;
 	unsigned long long _a6;
 	unsigned long long _a7[32];
 	char _a8[256];
 	char _a9[256];
 } cep_driver__mailBox;


extern void send_v2c_mail (int _a1, int _a2, v2c_top__mailBox *_a3);

extern void get_v2c_mail (int _a1, int _a2, v2c_top__mailBox *_a3);

#ifdef __cplusplus                          
 }                          
#endif

